# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yassineChatApp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


  profiles:
    active: dev

# Email Config
email:
  host: smtp.gmail.com
  port: 587
  id: <YOUR EMAIL ADDRESS>
  password: <YOUR PASSWORD>
  verify-email-host: http://localhost:${server.port}

# Security JWT
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000  # 24h in milliseconds


# Server
server:
  port: 8080

